### ISSUE TITLE
Multiple functions in a module compiles to empty function bodies

### ISSUE THREAD

**Issue by mrdziuban** [elixirscript/elixirscript#243]
I have a simple ElixirScript file that looks like this:

```elixir
defmodule App do
  @html ~s"""
    <input id="test-input">
  """

  def render, do: :document.getElementById("main") |> JS.update(%{"innerHTML" => @html})

  def bind_events do
    input = :document.getElementById("test-input")
    input.addEventListener("input", fn -> :console.log("input changed") end)
  end
end
```

When I try to compile this, I get the error:

```
** (EXIT from #PID<0.73.0>) an exception was raised:
    ** (CompileError) /Users/bryanjos/projects/basstype/elixirscript/lib/elixir_script.ex:6: you must require JS before invoking the macro JS.update/2
        (elixir) lib/macro.ex:1132: Macro.do_expand_once/2
        (elixir) lib/macro.ex:1159: Macro.expand_until/2
        (elixir_script) lib/elixir_script/translator.ex:572: ElixirScript.Translator.do_translate/2
        (elixir) lib/enum.ex:1325: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
        (elixir_script) lib/elixir_script/translator/kernel/special_forms/fn.ex:161: ElixirScript.Translator.Function.prepare_function_body/2
        (elixir_script) lib/elixir_script/translator/kernel/special_forms/fn.ex:99: ElixirScript.Translator.Function.make_function_body/2
        (elixir_script) lib/elixir_script/translator/kernel/special_forms/fn.ex:78: ElixirScript.Translator.Function.process_function_body/5
2017-02-21 23:15:53.447 [error] Process #PID<0.111.0> raised an exception
** (CompileError) /Users/bryanjos/projects/basstype/elixirscript/lib/elixir_script.ex:6: you must require JS before invoking the macro JS.update/2
    (elixir) lib/macro.ex:1132: Macro.do_expand_once/2
    (elixir) lib/macro.ex:1159: Macro.expand_until/2
    (elixir_script) lib/elixir_script/translator.ex:572: ElixirScript.Translator.do_translate/2
    (elixir) lib/enum.ex:1325: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir_script) lib/elixir_script/translator/kernel/special_forms/fn.ex:161: ElixirScript.Translator.Function.prepare_function_body/2
    (elixir_script) lib/elixir_script/translator/kernel/special_forms/fn.ex:99: ElixirScript.Translator.Function.make_function_body/2
    (elixir_script) lib/elixir_script/translator/kernel/special_forms/fn.ex:78: ElixirScript.Translator.Function.process_function_body/5
```

So I added `require JS` to the top of the module. This makes the file compile, but the compiled JavaScript looks like this:

```js
import Elixir from '../elixir/Elixir.Bootstrap';

import Elixir$ElixirScript$Kernel from '../elixir/Elixir.ElixirScript.Kernel';

import Elixir$JS from '../elixir/Elixir.JS';

const bind_events = Elixir.Core.Patterns.defmatch(Elixir.Core.Patterns.clause([], function() {
    let [input] = Elixir.Core.Patterns.match(Elixir.Core.Patterns.variable(), document.getElementById('test-input'));

    return input.addEventListener('input', Elixir.Core.Patterns.defmatch(Elixir.Core.Patterns.clause([], function() {
        return console.log('input changed');
    })));
}));

const render = Elixir.Core.Patterns.defmatch(Elixir.Core.Patterns.clause([], function() {
    return null;
}));

const html = '  <input id="test-input">\n';

export default {
    bind_events,
    render
};
```

Notice how the `render` function simply returns `null`. When I remove the `bind_events` function, the `render` function compiles properly.

So my questions are:

1. How can I get this module to compile properly?
2. Why does the error message point to `Users/bryanjos/projects/basstype/elixirscript`?

I'm using ElixirScript v0.25.0.

**Comment by mrdziuban** [comment]
This does not seem to be an issue with v0.24.0.

**Comment by bryanjos** [comment]
Looks like the  `:document.getElementById("main") |> JS.update(%{"innerHTML" => @html})` part is broken somewhere. Testing it with `JS.update(:document.getElementById("main"), %{"innerHTML" => @html})` seems to have produced the correct output. Definitely a bug.

As for why it's showing the that path, no idea, but I'll look into it

**Comment by bryanjos** [comment]
I think #244 will fix the path issue in the error. Have not come up with a solution for the first issue yet

**Comment by bryanjos** [comment]
@mrdziuban I fixed the piping issue with macros in the JS module. As far as the path in the error, As far as I can tell it's the path from where the files were when the escript was compiled. I'm going to look into ways to avoid having it there, but going to close this issue
