### ISSUE TITLE
Build failure with macOS 10.13 and Xcode 9

### ISSUE THREAD

**Issue by fxcoudert** [elixirscript/elixirscript#425]
Trying to build elixirscript on macOS 10.13 and Xcode 9 (within Homebrew) leads to `157 tests, 152 failures` in `mix test`. They all look like this:

```
  1) test match on tuple (ElixirScript.Translator.PatternMatching.Test)
     test/translator/pattern_matching_test.exs:204
     ** (EXIT from #PID<0.331.0>) an exception was raised:
         ** (ArgumentError) expected an Elixir module, got: :elixir
             (elixir) lib/module.ex:1148: Module.split/2
             (elixir_script) lib/elixir_script/translator/state.ex:28: anonymous fn/2 in ElixirScript.T
ranslator.State.build_standard_lib_map/0
             (elixir) lib/enum.ex:1811: Enum."-reduce/3-lists^foldl/2-0-"/3
             (elixir_script) lib/elixir_script/translator/state.ex:17: anonymous fn/2 in ElixirScript.T
ranslator.State.start_link/2
             (elixir) lib/agent/server.ex:8: Agent.Server.init/1
             (stdlib) gen_server.erl:365: :gen_server.init_it/2
             (stdlib) gen_server.erl:333: :gen_server.init_it/6
             (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```

Full logs can be found here: https://gist.github.com/91a5ade8ce135397a5437ddbe94f569a (in file `09.mix`).

**Comment by bryanjos** [comment]
Hi @fxcoudert,

I'm not sure what the issue is and I don't have high sierra yet to test it. I'm also trying to figure out how to "retire" elixirscript from homebrew since the newer versions will just be elixir libraries. ANy ideas how to do so? I also asked in another open issue, #422

**Comment by bryanjos** [comment]
Closing since I haven't heard anything else on it
