### ISSUE TITLE
comprehensions/generators

### ISSUE THREAD

**Issue by fazibear** [elixirscript/elixirscript#446]
Should they work?

Tried with `0.32` and `0.32`.

With `0.32` problem is the same as in #445 
With `0.31` got following error:

```
Uncaught TypeError: Cannot convert a Symbol value to a string
    at Array.toString (native)
    at Array.toString (native)
    at http://localhost:8080/elixir/elixirscript.build.js:1423:2057
    at Object._for (http://localhost:8080/elixir/elixirscript.build.js:1423:4708)
    at recur (http://localhost:8080/elixir/elixirscript.build.js:6366:48)
    at Object.trampoline$1 [as trampoline] (http://localhost:8080/elixir/elixirscript.build.js:1423:4297)
    at setup (http://localhost:8080/elixir/elixirscript.build.js:6382:44)
    at recur (http://localhost:8080/elixir/elixirscript.build.js:6396:40)
    at Object.trampoline$1 [as trampoline] (http://localhost:8080/elixir/elixirscript.build.js:1423:4297)
    at Object.start (http://localhost:8080/elixir/elixirscript.build.js:6402:44)
```

**Comment by bryanjos** [comment]
I'll have to take a look, but yes they should work
